/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntegrationGuideRouteImport } from './routes/integration-guide'
import { Route as IndexRouteImport } from './routes/index'

const IntegrationGuideRoute = IntegrationGuideRouteImport.update({
  id: '/integration-guide',
  path: '/integration-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integration-guide': typeof IntegrationGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integration-guide': typeof IntegrationGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integration-guide': typeof IntegrationGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/integration-guide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/integration-guide'
  id: '__root__' | '/' | '/integration-guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrationGuideRoute: typeof IntegrationGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/integration-guide': {
      id: '/integration-guide'
      path: '/integration-guide'
      fullPath: '/integration-guide'
      preLoaderRoute: typeof IntegrationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrationGuideRoute: IntegrationGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
